---
bases:
  - ../../base
  - ../../base/services
  - ../dbs/postgres
  - ../../base/migration

resources:
  - ./secrets.yaml

commonLabels:
  jacksondev: '1'

images:
  - name: boxyhq/jackson
    newTag: 1.12.0
