blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/boxyhq/jackson/discussions
    about: Ask a general question about the project on our GitHub Discussion page
