version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - 5433:5433
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    restart: always
  mongo:
    image: mongo:4.4.10
    ports:
      - 27017:27017
    restart: always
  mysql:
    image: mysql:8.0.31
    platform: linux/amd64
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: mysql
  maria:
    image: mariadb:10.10.2
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_DATABASE: mysql
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.6
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '123ABabc!'
