services:
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    restart: always
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    restart: always
  mysql:
    image: mysql:8.4.2
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: mysql
  maria:
    image: mariadb:11.5.2
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_DATABASE: mysql
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:2.0.0
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '123ABabc!'
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:2.5.2'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
  turso:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
      - '5001:5001'
    # environment:
    #   - SQLD_NODE=primary
    command: '/bin/sqld --enable-http-console'
    volumes:
      - ./docker/libsql:/var/lib/sqld
