version: '3'

x-uffizzi:
  ingress:
    service: saml-jackson
    port: 5225

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust

  saml-jackson:
    image: '${SAML_JACKSON_IMAGE}'
    depends_on:
      - db
    environment:
      SAML_AUDIENCE: https://saml.boxyhq.com
      JACKSON_API_KEYS: 'secret'
      IDP_ENABLED: true
      DB_ENGINE: sql
      DB_URL: postgres://postgres:postgres@localhost:5432/postgres
      DB_TYPE: postgres
      DB_TTL: 300
      DB_CLEANUP_LIMIT: 1000
      DB_PAGE_LIMIT: 50
      PRE_LOADED_CONFIG: /app/uffizzi/saml_config
    restart: unless-stopped
    ports:
      - '5225:5225'
    deploy:
      resources:
        limits:
          memory: 500M
