---
bases:
  - ../../base
  - ../../base/migration

resources:
  - ./secrets.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jackson
    path: ./jackson-deployment.yaml
  - target:
      group: batch
      version: v1
      kind: Job
      name: jackson-migrate-pg
    path: ./migratepg-job.yaml

images:
  - name: boxyhq/jackson
    newTag: 1.22.1
