name: Build PR Image
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    # Trigger only for PRs that target main branch
    branches:
      - main

jobs:
  build-jackson:
    name: Build and push `jackson`
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Generate Dockerfile
        id: generate-dockerfile
        run: |
          cd uffizzi
          ./create-dockerfile.sh

      - name: Generate UUID image name
        id: uuid
        run: echo "UUID_TAG=$(uuidgen)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.uffizzi.com/${{ env.UUID_TAG }}
          tags: |
            type=raw,value=60h

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./uffizzi/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true # makes image available to docker client
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Image to Uffizzi
        run: docker push registry.uffizzi.com/${{ env.UUID_TAG }}:60h

  render-compose-file:
    name: Render Docker Compose File
    # Pass output of this workflow to another triggered by `workflow_run` event.
    runs-on: ubuntu-latest
    needs:
      - build-jackson
    outputs:
      compose-file-cache-key: ${{ env.COMPOSE_FILE_HASH }}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Render Compose File
        run: |
          SAML_JACKSON_IMAGE=$(echo ${{ needs.build-jackson.outputs.tags }})
          export SAML_JACKSON_IMAGE
          # Render simple template from environment variables.
          envsubst < uffizzi/docker-compose.template.yml > docker-compose.rendered.yml
          cat docker-compose.rendered.yml
      - name: Upload Rendered Compose File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview-spec
          path: docker-compose.rendered.yml
          retention-days: 2
      - name: Serialize PR Event to File
        run: |
          cat << EOF > event.json
          ${{ toJSON(github.event) }} 

          EOF
      - name: Upload PR Event as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview-spec
          path: event.json
          retention-days: 2

  delete-preview:
    name: Call for Preview Deletion
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      # If this PR is closing, we will not render a compose file nor pass it to the next workflow.
      - name: Serialize PR Event to File
        run: |
          cat << EOF > event.json
          ${{ toJSON(github.event) }} 

          EOF
      - name: Upload PR Event as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview-spec
          path: event.json
          retention-days: 2
